# body:文字描述
# images:图片base64
# image_urls:图片地址(弃用)
# video_id:视频ID
# category_ids:分类IDs
# type:内容的类型
# issueInput:问答参数
# 参数示例
# {
#   "body":"视频里面是什么东西？",
#   "video_id":773,
#   "type": "ISSUE",
#   "issueInput": {
#     "gold":30
#   }
# }
mutation createPostMutation($body: String!,$qcvod_fileid:String,$images: [String!]){
  createPostContent(body:$body,qcvod_fileid:$qcvod_fileid,images:$images){
    id
    description
    user{
        id
        avatar
        name
    }
    video{
      url
      cover_url
    }
    status
    review_id
    review_day
  }
}

#看视频奖励
mutation VideoPlayReward($input: videoPlayReport) {
    videoPlayReward(input: $input) {
        gold
    }
}

# 删除
mutation deleteArticle($id: Int!) {
    deleteArticle(id: $id) {
        id
    }
}

# 采集粘贴板视频
mutation resolveDouyinVideo($share_link: String!) {
    resolveDouyinVideo(share_link: $share_link) {
        id
    }
}

# 点击视频流广告
mutation clickVideoAD {
    clickAD {
        id
        created_at
        amount
        message
    }
}

# 点击动态广场信息流广告
mutation clickFeedAD {
    clickFeedAD2 {
        amount
        message
    }
}

# 不感兴趣
mutation addArticleBlockMutation($id: Int!) {
    addArticleBlock(id: $id) {
        id
    }
}

# 收藏，取消收藏
mutation toggleFavoritedMutation($id: Int!) {
    toggleFavorited(article_id: $id) {
        faved_id
        created_at
    }
}
